{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-nextgen
  annotations:
    {{- if .Values.global.ingress.objects.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.global.ingress.objects.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /cv/api/$2
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: cv-nextgen
                port:
                  number: {{ .Values.service.port }}
            path: /cv/api(/|$)(.*)
            pathType: ImplementationSpecific
    {{- range .Values.global.ingress.hosts }}
      host: {{ . | quote }}
    {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.global.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
{{- end }}