apiVersion: v1
kind: ConfigMap
metadata:
  name: verification-svc
  namespace: {{ .Release.Namespace }}
data:
  DEPLOY_MODE: KUBERNETES_ONPREM
  LOGGING_LEVEL: {{ .Values.appLogInfo | quote }}
  MANAGER_URL: http://harness-manager:9090/api/
  MEMORY: {{ .Values.java.memory | quote }}
  VERIFICATION_PORT: {{ .Values.service.port | quote }}
  VERSION: 1.0.77622
  VERIFICATION_SERVICE_SECRET: 59MR5RlVARcdH7zb7pNx6GzqiglBmXR8
  {{ if .Values.global.mongoSSL }}
  MONGO_SSL_CONFIG: "true"
  MONGO_SSL_CA_TRUST_STORE_PATH: /opt/harness/keystore.jks
  MONGO_SSL_CA_TRUST_STORE_PASSWORD: password
  {{ end }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}