apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: template-service
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: template-service
