apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "template-service.labels" . | nindent 4 }}
  name: template-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc-template
    port: {{ .Values.service.grpcport }}
    protocol: TCP
    targetPort: {{ .Values.service.grpcport }}
  - name: http-template
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  - name: grpc-gitsync
    port: {{ .Values.service.gitsyncgrpcport }}
    protocol: TCP
    targetPort: {{ .Values.service.gitsyncgrpcport }}
  selector:
    {{- include "template-service.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{.Values.service.type}}
